FROM node:20-alpine

# Set the working directory in the container
WORKDIR /App

# Copy the requirements file into the container
COPY package.json .

# Install any needed packages specified in requirements.txt
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Run database migrations and start the Django development server
CMD ["npm","run","dev"]